server:
  port: 6666
  app-name: zuul-gateway-server
  discover:
    hostname: 192.168.1.197
    port: 7000
  eureka:
    user:
      name: zhangsan
      password: 123

zuul:
  prefix: /qs
  ignored-services: "*"
  routes:
    user:
      serviceId: user-center-provider
      path: /user/**
    product:
      serviceId: product-center-provider
      path: /product/**

spring:
    application:
      name: ${server.app-name}

eureka:
  client:
    service-url:
      defaultZone: http://${server.discover.hostname}:${server.discover.port}/eureka/
#      defaultZone: http://${server.eureka.user.name}:${server.eureka.user.password}@${server.discover.hostname}:${server.discover.port}/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    #表示eureka client间隔多久去拉取服务注册信息，默认为30秒，
    # 对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
  instance:
    instance-id: ${server.app-name}-${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health

# admin server 配置 允许访问权限
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


logging:
  level:
    root: info

info:
  app.name: ${server.app-name}
  company.name: qs.game
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"
  spring-cloud-version: "@spring.cloud.verion@"