server:
  port: 7200
  app-name: memcached-provider
  discover:
    hostname: 192.168.1.104
    port: 7000

spring:
  application:
    name: ${server.app-name}

eureka:
  client:
    service-url:
      defaultZone: http://${server.discover.hostname}:${server.discover.port}/eureka/
  instance:
    instance-id: ${server.app-name}-${server.port}
    prefer-ip-address: true

## Memcache 配置 ##
memcache:
  servers:
    - 192.168.1.197:11211
  weights:
    - 5
  failover: true
  initConn: 20
  minConn: 10
  maxConn: 30
  maintSleep: 3000
  nagel: false
  socketTO: 3000
  aliveCheck: true
  connectionPoolSize: 1
  connectTimeout: 60000

logging:
  level:
    root: info

info:
  app.name: ${server.app-name}
  company.name: qs.game
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"
  spring-boot-version: "@project.parent.version@"