spring:
  profiles:
    active:
    - dev


---

server:
  port: 7100
  app-name: zhuozun-admin-server
  discover:
    hostname: 192.168.1.104
#    hostname: 192.168.1.204
    port: 7000

spring:
  profiles: dev
  application:
    name: ${zhuozun-admin-server}-{spring.profiles}
    admin:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    #表示eureka client间隔多久去拉取服务注册信息，默认为30秒，
    # 对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
    service-url:
      defaultZone: http://${server.discover.hostname}:${server.discover.port}/eureka/
  instance:
    instance-id: ${server.app-name}-${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
#    metadata-map:
#      user.name: "user"         #These two are needed so that the server
#      user.password: "password" #can access the protected client endpoints



# admin server 配置 允许访问权限（此处访问自己）
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    root: info


# 引用监控限制内容Map <Key String>
info:
  artifact : ${server.discover.hostname}
  name: ${spring.application.name}
  description: 应用监控中心
  version : V1.0
  spring-boot-version: "@springboot.verion@"
  spring-cloud-version: "@spring.cloud.version@"

---













server:
  port: 7100
  app-name: zhuozun-admin-server
  discover:
    hostname: 192.168.1.104
#    hostname: 192.168.1.204
    port: 7000

spring:
  profiles: local
  application:
    name: ${zhuozun-admin-server}-{spring.profiles}
    admin:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    #表示eureka client间隔多久去拉取服务注册信息，默认为30秒，
    # 对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
    service-url:
      defaultZone: http://${server.discover.hostname}:${server.discover.port}/eureka/
  instance:
    instance-id: ${server.app-name}-${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
#    metadata-map:
#      user.name: "user"         #These two are needed so that the server
#      user.password: "password" #can access the protected client endpoints



# admin server 配置 允许访问权限（此处访问自己）
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    root: info


# 引用监控限制内容Map <Key String>
info:
  artifact : ${server.discover.hostname}
  name: ${spring.application.name}
  description: 应用监控中心
  version : V1.0
  spring-boot-version: "@springboot.verion@"
  spring-cloud-version: "@spring.cloud.version@"

---











server:
  port: 7100
  app-name: zhuozun-admin-server
  discover:
    hostname: 192.168.1.104
#    hostname: 192.168.1.204
    port: 7000

spring:
  profiles: test
  application:
    name: ${zhuozun-admin-server}-{spring.profiles}
    admin:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    #表示eureka client间隔多久去拉取服务注册信息，默认为30秒，
    # 对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
    service-url:
      defaultZone: http://${server.discover.hostname}:${server.discover.port}/eureka/
  instance:
    instance-id: ${server.app-name}-${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
#    metadata-map:
#      user.name: "user"         #These two are needed so that the server
#      user.password: "password" #can access the protected client endpoints



# admin server 配置 允许访问权限（此处访问自己）
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    root: info


# 引用监控限制内容Map <Key String>
info:
  artifact : ${server.discover.hostname}
  name: ${spring.application.name}
  description: 应用监控中心
  version : V1.0
  spring-boot-version: "@springboot.verion@"
  spring-cloud-version: "@spring.cloud.version@"

---






server:
  port: 7100
  app-name: zhuozun-admin-server
  discover:
    hostname: 192.168.1.104
#    hostname: 192.168.1.204
    port: 7000

spring:
  profiles: prod
  application:
    name: ${zhuozun-admin-server}-{spring.profiles}
    admin:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    #表示eureka client间隔多久去拉取服务注册信息，默认为30秒，
    # 对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
    service-url:
      defaultZone: http://${server.discover.hostname}:${server.discover.port}/eureka/
  instance:
    instance-id: ${server.app-name}-${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
#    metadata-map:
#      user.name: "user"         #These two are needed so that the server
#      user.password: "password" #can access the protected client endpoints



# admin server 配置 允许访问权限（此处访问自己）
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    root: info


# 引用监控限制内容Map <Key String>
info:
  artifact : ${server.discover.hostname}
  name: ${spring.application.name}
  description: 应用监控中心
  version : V1.0
  spring-boot-version: "@springboot.verion@"
  spring-cloud-version: "@spring.cloud.version@"
