server:
  port: 7000
  app-name: discover-server
  discover:
    hostname: 192.168.1.104
#    hostname: 192.168.1.204
    port: ${server.port}
  eureka:
    user:
      name: zhangsan
      password: 123

eureka:
  instance:
    hostname: ${server.discover.hostname}
  client:
    register-with-eureka: false # 是否要注册到服务器端，因为此处为Eureka Server，所以设定为false
    fetch-registry: false # 是否从服务器端取得注册信息，因为此处为Eureka Server，所以设定为false
    service-url:
      defaultZone: http://${server.discover.hostname}:${server.discover.port}/eureka/
      # defaultZone: http://${server.eureka.user.name}:${server.eureka.user.password}@${server.discover.hostname}:${server.discover.port}/eureka/

spring:
  application:
    name: ${server.app-name}
#  security:
#    user:
#      name: ${server.eureka.user.name}
#      password: ${server.eureka.user.password}


logging:
  level:
    root: info

info:
  app.name: ${server.app-name}
  company.name: qs.game
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"
  spring-cloud-version: "@spring.cloud.verion@"

