#不能用localhost,否则启动报异常:Unresolved address
#tcp监听的端口
netty:
  websocket:
    port: 9002
  boss:
    thread:
      count: 2  # bossGroup的线程数
  worker:
    thread:
      count: 2  # worker的线程数

server:
  port: 8600
  app-name: websocket-server
  discover:
    hostname: 192.168.1.104
    port: 7000
  eureka:
    user:
      name: zhangsan
      password: 123

spring:
  application:
    name: ${server.app-name}
  freemarker:
    suffix: .ftl
  redis:
    database: 14
    host: 192.168.1.128
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        min-idle: 8
        max-idle: 0

eureka:
  client:
    service-url:
      defaultZone: http://${server.discover.hostname}:${server.discover.port}/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${server.app-name}-${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health

# admin server 配置 允许访问权限
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    root: info
    io: # 指定包输入日志
      swagger: error

info:
  app.name: ${server.app-name}
  company.name: qs.game
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"
  spring-cloud-version: "@spring.cloud.verion@"

# https://www.jianshu.com/p/222fe9f2a564
# https://blog.csdn.net/li6151770/article/details/73546565